version: 2.1

orbs:
  node: circleci/node@5

references:
  node_executor: &node_executor
    docker:
      - image: &node_image node:16.10.0-alpine

jobs:
  checkout-install-persist:
    <<: *node_executor
    steps:
      - run:
          name: Install git and ssh
          command: apk add git openssh-client
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *node_executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Generate image
          command: node ./index.js

workflows:
  version: 2

  test:
    jobs:
      - checkout-install-persist
      - test:
          requires:
            - checkout-install-persist
